[package]
name = "lester"
version = "0.0.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "Lester, Victorâ€™s cousin, makes raster graphics"
repository = "https://github.com/SimonSapin/victor"

[lib]
test = false
doctest = false

[build-dependencies]
pkg-config = "0.3.9"
